import LawMain from "@/LAWmain/Index";
import "./globals.css";
import NavbaarPage from "../../Layout/Header/NavbaarPage";
import Footer from "../../Layout/Footer/Index";
import ShapeContainer from "@/Components/ShapeContainer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {

  return (
    <html lang="en">
      <body className="">
        <ShapeContainer>
        <NavbaarPage />
        {children}
        <Footer /> 
        </ShapeContainer>
      </body>
    </html>
  );
}
